### ISSUE TITLE
Make Quantity a value class

### ISSUE THREAD

**Issue by zainab-ali** [to-ithaca/libra#2]
extending `AnyVal` causes the divide test in the `QuantitySpec` to fail with the following runtime error:
```
[info] libra.QuantitySpec *** ABORTED ***
[info]   java.lang.ClassFormatError: Duplicate method name&signature in class file libra/ops/quantity$Divide$$anon$5
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
```
The divide doctest fails with the error:
```
[info] libra.quantityDoctest *** ABORTED ***
[info]   java.lang.ClassFormatError: libra/ops/quantity$Divide$$anon$5
[info]   at libra.ops.quantity$Divide$.quantityDivide(quantity.scala:121)
[info]   at libra.quantityDoctest$$anonfun$8$$anonfun$apply$mcV$sp$7.apply$mcV$sp(quantityDoctest.scala:114)
```
The bytecode needs to be investigated to see why this is, and why it only happens to the `Divide` typeclass.

**Comment by zainab-ali** [comment]
The problem was something to do with inheriting from `DepFn` - it wen't away when I removed this inheritance.  No idea why this relates to value classes.

This will be released as part of `0.2.0`
